<style type="text/css">

  body{
  padding-left: 11em;
   padding-right: 11em;
   padding-top: 5em;
  font-family: Georgia, "Times New Roman",
        Times, serif;
  color: red;
   font-size: 12pt;
font-weight: 300;
text-align:justify;
   margin: 0em auto;
  width: 1200px;
  background-image: url("images/DSCN5018.gif")
}
  h1, h2, h3
{
  margin: 0;
  padding: 0;
  color: black;
}
p
{
margin-top: 1px;
line-height: 180%;
color: red;
}

</style>